### ISSUE TITLE
Changing the Initialization vector?

### ISSUE THREAD

**Issue by NoMan2000** [ioncube/php-openssl-cryptor#3]
I made a pull request to remove the call to mcrypt that's still in the file.  It can be replaced with an openSSL call, your code will still work.  

       // Build an initialisation vector	
       // Replacing all mcrypt calls
        // $iv = mcrypt_create_iv($this->iv_num_bytes, MCRYPT_DEV_URANDOM);
       
        // Build an initialisation vector
        $iv = openssl_random_pseudo_bytes($this->iv_num_bytes, $isStrongCrypto);
        if (!$isStrongCrypto) {
            throw new \Exception("Not a strong key");
        }

**Comment by NoMan2000** [comment]
Ref: https://github.com/ioncube/php-openssl-cryptor/pull/4

**Comment by nickion** [comment]
Pull request merged a while back; thanks again for improving the code.
